apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: web-app-experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/web-app-experiment-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: FRONTEND_URL
              value: "<frontend-loadbalancer-url>"  # Replace with EKS frontend URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"