apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web-app-experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/web-app-experiement-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service.web-app-experiment.svc.cluster.local:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"